blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/yourusername/pr-approval-finder/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/yourusername/pr-approval-finder/security/policy
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://github.com/yourusername/pr-approval-finder#readme
    about: Check out our comprehensive documentation
  - name: 💡 Feature Discussion
    url: https://github.com/yourusername/pr-approval-finder/discussions/categories/ideas
    about: Discuss feature ideas before creating a formal request 