name: Quality Gate

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install client dependencies
      run: cd client && npm ci
    
    - name: Install server dependencies
      run: cd server && npm ci
    
    - name: Check code formatting
      run: npm run format:check
    
    - name: Run linting
      run: npm run lint
    
    - name: Build client
      run: cd client && CI=false npm run build
    
    - name: Run tests (if available)
      run: |
        echo "Checking for tests..."
        
        # Check if test files exist in client
        if [ -d "client/src" ] && find client/src -name "*.test.js" -o -name "*.test.jsx" -o -name "*.spec.js" -o -name "*.spec.jsx" | grep -q .; then
          echo "Running client tests..."
          cd client && npm test -- --watchAll=false --passWithNoTests
        else
          echo "No test files found in client/src"
        fi
        
        # Check if test files exist in server
        if [ -d "server" ] && find server -name "*.test.js" -o -name "*.spec.js" | grep -q .; then
          echo "Running server tests..."
          cd server && npm test
        else
          echo "No test files found in server"
        fi
        
        echo "Test check completed successfully"
    
    - name: Check for security vulnerabilities
      run: |
        npm audit --audit-level=moderate
        cd client && npm audit --audit-level=moderate
        cd ../server && npm audit --audit-level=moderate 